# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "リリースAPKファイルを生成"
  lane :create_release_apk do
    # クリーンビルドしてリリースAPKを作成する
    gradle(task: "clean assembleRelease")
  end

  desc "認証済みリリースAABファイルを生成してGoogle Play Consoleへアップロード"
  lane :build_aab do
    # AABファイル生成
    gradle(
      task: "clean bundle",
      build_type: "release",
      properties: {
        # KeyStore情報を指定して認証
        "android.injected.signing.store.file" => ENV['KEY_FILE_PATH'],
        "android.injected.signing.store.password" => ENV['KEY_STORE_PASS'],
        "android.injected.signing.key.alias" => ENV['KEY_STORE_ALIAS'],
        "android.injected.signing.key.password" =>  ENV['KEY_STORE_PASS'],
      }
    )
    # Google Play Consoleへアップロード    
    upload_to_play_store(
        # 内部テストとしてアップロード
        track: "internal",
        # リリースのステータスを下書きとする
        release_status: "draft",
        # APKファイルのアップロードをスキップ
        skip_upload_apk: true,
        # 各メタデータのアップロードをスキップ
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
    )
  end


end
