# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "リリースAPKファイルを生成"
  lane :create_release_apk do
    # クリーンビルドしてリリースAPKを作成する
    gradle(task: "clean assembleRelease")
  end

  desc "リリースAABファイルを生成"
  lane :build_aab do
    gradle(
      task: "clean bundle",
      build_type: "release"
    )
    upload_to_play_store(
        track: "internal",
        release_status: "draft",
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
    )
  end


end
